version: 1.0.{build}

environment:
  my_variable:
    secure: lBislJUl6RP/4mh6NOGZcA==

install:
  - ps: wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-win32-x86.zip -OutFile cmake.zip
  - cmd: 7z x cmake.zip -o"C:\Program Files (x86)\" -y
  - cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\Program Files (x86)\cmake-3.0.2-win32-x86\bin
  - cmd: cmake --version
  - ps: wget https://s3.amazonaws.com/biibinaries/release/2.0.1/bii-win_2_0_1.exe -OutFile bii-win.exe
  - cmd: bii-win.exe /VERYSILENT
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii
  - cmd: bii -v
  - ps: wget https://s3.amazonaws.com/biibinaries/thirdparty/MinGW.zip -OutFile mingw.zip
  - cmd: 7z x mingw.zip -oC:\MinGW -y
  - cmd: set PATH=%PATH:Git\bin=%;C:\MinGW\bin
  - cmd: del bii-win.exe
  - cmd: del cmake.zip

before_build:
  - cmd: bii init myproject
  - cmd: cd myproject
  - cmd: bii open lasote/docker_client

build_script:
  - cmd: bii cpp:build

test_script:
  - cmd: bin\lasote_docker_client_main.exe

# to run your custom scripts instead of provider deployments
deploy_script:
  - cmd: bii user lasote -p %secured_passwd%
  - cmd: bii publish

